version: '3'
services:

  nginx:
    image: {{ nginx_certbot_image }}
    container_name: nginx
    restart: unless-stopped
    networks:
      - nginxtest_network
    depends_on:
      - vouch
    ports:
      - '80:80'
      - '443:443'
    environment:
      CERTBOT_EMAIL: {{ certbot_email }}
      SERVER_URL: {{ server_url }}
      USE_LOCAL_CA: {{ certbot_use_local_ca }}
      DEBUG: {{ certbot_debug }}
    volumes:
      - {{ docker_nginxtest_dir }}/nginx_html:/html:ro
      - {{ docker_nginxtest_dir }}/nginx_logs:/logs
      - {{ docker_nginxtest_dir }}/nginx_secrets:/etc/letsencrypt
      - {{ docker_nginxtest_dir }}/nginx_user_conf.d:/etc/nginx/user_conf.d

  vouch:
    image: quay.io/vouch/vouch-proxy:alpine-0.35.1
    container_name: vouch
    restart: unless-stopped
    networks:
      - nginxtest_network
    volumes:
      - {{ docker_nginxtest_dir }}/vouch.config/config:/config

networks:
  nginxtest_network:
    name: nginxtest_network
